version: "3"

services:
  frontend:
    build: ./frontend
    container_name: learn-docker-frontend
    command: serve build -l 3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - learn-docker-network

  api:
    build: ./api
    container_name: learn-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - learn-docker-network

  api_db:
    image: mongo:latest
    container_name: learn-docker-api_db
    volumes:
      - mongodb_api:/data/db
    networks:
      - learn-docker-network

  auth:
    build: ./auth
    container_name: learn-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - learn-docker-network

  auth_db:
    image: mongo:latest
    container_name: learn-docker-auth_db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - learn-docker-network

  nginx:
    image: nginx:stable-alpine
    container_name: learn-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - learn-docker-network

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  learn-docker-network:
    driver: bridge
