version: '3'

services:
  api:
    build: ./api
    command: npm run start
    ports:
      - '4001:4001'
    environment:
      - PORT=4001
      - HOST=http://customhost.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  api_db:
    image: mongo:latest