version: '3'

services:
  api:
    build: ./api
    container_name: learn-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - '4001:4001'
    environment:
      - PORT=4001
      - HOST=http://customhost.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: learn-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
    container_name: learn-docker-api_db
    volumes:
      - mongodb_api:/data/db

  auth_db:
    image: mongo:latest
    container_name: learn-docker-auth_db
    volumes:
      - mongodb_api:/data/db

volumes:
  mongodb_api: